const skillGroups={programming:['Python','C','C++','SQL'],ai:['Machine Learning','Scikit-learn','PyTorch','NLP','Computer Vision','Recommendation Systems','Feature Engineering','Model Evaluation','RAG','OCR'],data:['Power BI','DAX','Pandas','NumPy','Data Cleaning','Data Validation','EDA','Data Visualization','RFM Analysis','K-Means Clustering','Sales Forecasting'],build:['FastAPI','Django','React','Streamlit','REST APIs','PostgreSQL','MongoDB','ChromaDB'],tools:['Git','FAISS','OpenCV','Cloud Computing Basics','Edge Computing']};
const projects=[
 {title:'Revenue Analytics',category:'Data Analytics',tag:'Data Analytics / BI',description:'An end-to-end retail analytics system using 32K+ transaction records, from data validation and normalized storage through segmentation, forecasting, and decision-ready dashboards.',features:['Data cleaning & validation','RFM customer analysis','K-Means segmentation','Chronological sales forecasting','Power BI dashboards & DAX KPIs'],tech:['Python','Pandas','SQL','PostgreSQL','Power BI','Scikit-learn'],status:'Strongest analytics project',featured:true},
 {title:'VeriFact AI',category:'AI / ML',tag:'AI / NLP / RAG',description:'A full-stack platform designed to analyze and verify claims from text, images, screenshots, and URLs with explainable evidence and verdicts.',features:['AI claim extraction','Evidence retrieval & RAG','OCR and image analysis','Credibility scoring','Analytics dashboard & authentication'],tech:['FastAPI','React / Next.js','PostgreSQL','ChromaDB','NLP','RAG','OCR'],status:'In development · Improving real-data reliability'},
 {title:'Hand Gesture Recognition',category:'Computer Vision',tag:'Computer Vision / ML',description:'A real-time hand gesture recognition system identifying 36 unique gesture classes representing alphabets and digits.',features:['Hand landmark extraction','Random Forest classification','Low-latency inference','Real-time recognition'],tech:['Python','OpenCV','Random Forest','Machine Learning'],metrics:'36 classes · 3,200+ samples · 99% accuracy',status:'Project completed',github:'https://github.com/SamruddhiSKa/Sign-to-Text-Converter'},
 {title:'Movie Recommendation System',category:'AI / ML',tag:'AI / ML / Recommendations',description:'An AI-powered hybrid movie recommendation system combining multiple approaches to generate personalized, contextual, and explainable suggestions.',features:['Content-based filtering & TF-IDF','Collaborative filtering & SVD','Neural Collaborative Filtering','Mood and time-aware recommendations','NLP discovery & FAISS search'],tech:['PyTorch','FAISS','FastAPI','React','PostgreSQL'],status:'In development'},
 {title:'PDF Converter',category:'Software Development',tag:'Software Development / Tool',description:'Project details to be added.',features:['Features to be added'],tech:['Technologies to be added'],status:'Details to be added'},
 {title:'SprintX',category:'Software Development',tag:'Software Development / Project',description:'Project details to be added.',features:['Features to be added'],tech:['Technologies to be added'],status:'Details to be added'}
];
const experience=[['Google AI/ML Virtual Internship','EduSkills / Google for Developers','Virtual Internship','Artificial Intelligence · Machine Learning · Python · Data Processing · ML workflows'],['Siemens Data Science Master Virtual Internship','EduSkills / Siemens','Virtual Internship / Training','Data Science · Machine Learning · Data Analytics · RapidMiner · Data preprocessing · Visualization · Evaluation'],['SmartBridge Internship','[Add role / track]','Current · Details to be added','Technologies · Responsibilities · Start date · End date [add details]'],['Web Development, Python-Django Virtual Intern','Elite Softwares Pvt Ltd, Pune','Dec 2024 – Jan 2025','Developed Django web applications, backend logic, RESTful APIs in Python, database-backed CRUD operations, and modular MVC-structured applications.']];
const certifications=[['Power BI Bootcamp','Nucleus','Training'],['Machine Learning I','Columbia University','Course'],['AI Agents','Google / Kaggle','Training'],['AI Principles with Edge Computing','Coursera','Course']];

const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
function renderSkills(group='programming'){const names={programming:'Programming',ai:'AI & Machine Learning',data:'Data & Analytics',build:'Backend & Development',tools:'Tools & Concepts'};$('#skill-title').textContent=names[group];$('#skill-list').innerHTML=skillGroups[group].map(skill=>`<span>${skill}</span>`).join('');const index=Object.keys(skillGroups).indexOf(group)+1;$('.skill-count').textContent=`0${index} — 05`}
function renderProjects(filter='All'){const shown=filter==='All'?projects:projects.filter(project=>project.category===filter||project.tag.includes(filter));$('#project-grid').innerHTML=shown.map((project,index)=>`<article class="project-card ${project.featured?'featured':''} reveal visible"><div class="project-top"><span class="tag">${project.tag}</span><span class="project-index">0${projects.indexOf(project)+1}</span></div><h3>${project.title}</h3><p>${project.description}</p><div class="project-bottom"><div><div class="tech-row">${project.tech.map(tech=>`<span>${tech}</span>`).join('')}</div>${project.metrics?`<small class="project-metrics">${project.metrics}</small>`:''}</div><button class="project-open" data-project="${projects.indexOf(project)}" aria-label="Open details for ${project.title}"><i data-lucide="arrow-up-right"></i></button></div></article>`).join('');lucide.createIcons();$$('.project-open').forEach(button=>button.addEventListener('click',()=>openModal(Number(button.dataset.project))))}
function renderExperience(){$('#experience-list').innerHTML=experience.map((item,index)=>`<article class="timeline-item reveal"><div><small>0${index+1} / ${item[2]}</small><h3>${item[0]}</h3></div><p>${item[1]}</p><p>${item[3]}</p></article>`).join('')}
function renderCertifications(){$('#cert-grid').innerHTML=certifications.map((item,index)=>`<article class="cert-card reveal"><span>0${index+1} · ${item[2]}</span><h3>${item[0]}</h3><p>${item[1]} · Date [add date]</p></article>`).join('')}
function openModal(index){const project=projects[index];$('#modal-category').textContent=project.tag;$('#modal-title').textContent=project.title;$('#modal-description').textContent=project.description;$('#modal-features').innerHTML=project.features.map(feature=>`<li>${feature}</li>`).join('');$('#modal-tech').innerHTML=project.tech.map(tech=>`<span>${tech}</span>`).join('');$('#modal-status').textContent=project.status;const link=$('#modal-github');if(project.github){link.href=project.github;link.style.display='inline-flex'}else{link.style.display='none'}$('#project-modal').classList.add('open');$('#project-modal').setAttribute('aria-hidden','false');lucide.createIcons()}
function closeModal(){$('#project-modal').classList.remove('open');$('#project-modal').setAttribute('aria-hidden','true')}
renderSkills();renderProjects();renderExperience();renderCertifications();
lucide.createIcons();
$$('.skill-tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.skill-tab').forEach(item=>item.classList.remove('active'));tab.classList.add('active');renderSkills(tab.dataset.skill)}));
$$('.filter').forEach(filter=>filter.addEventListener('click',()=>{$$('.filter').forEach(item=>item.classList.remove('active'));filter.classList.add('active');renderProjects(filter.dataset.filter)}));
$('.modal-close').addEventListener('click',closeModal);$('.modal-backdrop').addEventListener('click',closeModal);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal()});
$('.menu-toggle').addEventListener('click',()=>{$('.nav-links').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',$('.nav-links').classList.contains('open'))});$$('.nav-links a').forEach(link=>link.addEventListener('click',()=>$('.nav-links').classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.13});$$('.reveal').forEach(element=>observer.observe(element));
const metricObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){const node=entry.target;const target=Number(node.dataset.count);let current=0;const isDecimal=String(target).includes('.');const duration=850;const start=performance.now();function tick(now){const progress=Math.min((now-start)/duration,1);current=target*progress;node.textContent=isDecimal?current.toFixed(2):Math.floor(current).toLocaleString();if(progress<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);metricObserver.unobserve(node)}}),{threshold:.8});$$('[data-count]').forEach(metric=>metricObserver.observe(metric));
