const skillGroups={programming:['Python','C','C++','SQL'],ai:['Machine Learning','Scikit-learn','PyTorch','NLP','Computer Vision','Recommendation Systems','Feature Engineering','Model Evaluation','RAG','OCR','MediaPipe'],data:['Power BI','DAX','Pandas','NumPy','Data Cleaning','Data Validation','EDA','Data Visualization','RFM Analysis','K-Means Clustering','Sales Forecasting'],build:['FastAPI','Django','React','Next.js','REST APIs','Node.js','Express.js','PostgreSQL','MongoDB','ChromaDB'],tools:['Git','GitHub','FAISS','OpenCV','WebRTC','Cloud Computing Basics','Edge Computing']};
const projects=[
 {title:'AI-Powered Sales and Revenue Analytics System',category:'Data Analytics',tag:'Data Analytics / BI / ML',description:'An end-to-end retail analytics platform that transforms 32K+ transaction records into actionable insights through SQL, customer segmentation, forecasting, and interactive Power BI dashboards.',features:['Raw data → cleaning → PostgreSQL → SQL analytics','Revenue, profitability, product, customer, and regional analysis','RFM analysis and K-Means segmentation','Chronological sales forecasting','Power BI dashboards and DAX KPIs'],tech:['Python','Pandas','SQL','PostgreSQL','Power BI','DAX','Scikit-learn','RFM Analysis','K-Means'],metrics:'32K+ transactions analyzed',status:'Featured project',featured:true},
 {title:'VeriFact AI',category:'AI / ML',tag:'AI / NLP / RAG / Full Stack',description:'A full-stack AI platform designed to analyze claims from text, images, screenshots, and URLs and provide evidence-based fact-verification results.',features:['Claim extraction and evidence retrieval','RAG pipeline and credibility analysis','Explainable verdicts: TRUE, FALSE, MISLEADING, PARTIALLY TRUE, UNVERIFIED','Multimodal input, OCR, and multilingual support for English, Hindi, and Marathi','JWT authentication and analytics'],tech:['React / Next.js','FastAPI','PostgreSQL','ChromaDB','NLP','RAG','OCR','JWT Authentication'],status:'IN DEVELOPMENT',featured:true},
 {title:'Real-Time Sign-to-Text Converter',category:'Computer Vision',tag:'Computer Vision / ML / Real-Time',description:'A real-time computer vision system that recognizes hand gestures representing alphabets and digits using hand landmarks and machine learning.',features:['Camera → hand detection → 21 landmarks → normalized features','100-tree Random Forest classifier with 42 hand-landmark features','36 unique gesture classes from 3,200+ samples','99% accuracy and 15+ FPS on Android browsers through WebRTC-based deployment','Submitted and accepted for review/presentation: Real-Time Sign-to-Text Conversion using Machine Learning and Computer Vision'],tech:['Python','OpenCV','MediaPipe','Scikit-learn','Random Forest','WebRTC'],metrics:'36 classes · 3,200+ samples · 99% accuracy · 15+ FPS',status:'Completed project',github:'https://github.com/SamruddhiSKa/Sign-to-Text-Converter'},
 {title:'CineMatch',category:'AI / ML',tag:'AI / ML / Recommendations',description:'A hybrid recommendation platform combining content-based filtering, collaborative filtering, neural recommendation, contextual personalization, and similarity search.',features:['TF-IDF content-based filtering and SVD collaborative filtering','PyTorch Neural Collaborative Filtering','Mood and time-of-day personalization','FAISS similarity search and NLP chatbot discovery','RMSE ≈ 1.04, Precision@10, and Hit Ratio@10 evaluation'],tech:['Scikit-learn','Surprise','PyTorch','FAISS','React','FastAPI','PostgreSQL'],status:'IN DEVELOPMENT · Improving metadata, posters, and recommendation presentation'},
 {title:'Universal File to PDF Converter',category:'Software Development',tag:'Full Stack / Document Processing',description:'A full-stack web application that converts multiple file formats into PDF through a responsive drag-and-drop interface and server-side conversion pipeline.',features:['Text, image, Word, Excel, and PowerPoint conversion','Drag-and-drop upload and downloadable PDF workflow','Page size, orientation, and margin controls','Format detection, processing, conversion, and fallback handling'],tech:['Node.js','Express.js','JavaScript','pdf-lib','Mammoth','XLSX','Sharp','Playwright'],status:'COMPLETED PROJECT'},
 {title:'SprintX',category:'Software Development',tag:'Web Development / Analytics',description:'A fictional academic sneaker e-commerce project combining responsive web development, digital marketing, Google Analytics 4, Google Ads, Search Console, and conversion tracking.',features:['Product browsing, filtering, collections, cart, and checkout','GA4 events: page views, sessions, scrolls, engagement, and outbound clicks','Google Ads search/display planning and Search Console integration','Funnel: website visit → product view → cart → checkout','Analytics: 38 sessions, 108 page views, 24 active users, 4.50 views per active user'],tech:['HTML','CSS','JavaScript','Netlify','Google Analytics 4','Google Ads','Google Search Console'],status:'COMPLETED ACADEMIC PROJECT · Fictional brand'},
];
const experience=[['Google AI/ML Virtual Internship','EduSkills / Google for Developers','Virtual Internship','Artificial Intelligence · Machine Learning · Python · Data Processing · ML workflows'],['Siemens Data Science Master Virtual Internship','EduSkills / Siemens','Virtual Internship / Training','Data Science · Machine Learning · Data Analytics · RapidMiner · Data preprocessing · Visualization · Evaluation'],['SmartBridge Internship','SmartBridge','Current','Current internship experience'],['Web Development, Python-Django Virtual Intern','Elite Softwares Pvt Ltd, Pune','Dec 2024 – Jan 2025','Developed Django web applications, backend logic, RESTful APIs in Python, database-backed CRUD operations, and modular MVC-structured applications.']];
const certifications=[['Power BI Bootcamp','Nucleus','Training'],['Machine Learning I','Columbia University','Course'],['AI Agents','Google / Kaggle','Training'],['AI Principles with Edge Computing','Coursera','Course']];

const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
function renderSkills(group='programming'){const names={programming:'Programming',ai:'AI & Machine Learning',data:'Data & Analytics',build:'Backend & Development',tools:'Tools & Concepts'};$('#skill-title').textContent=names[group];$('#skill-list').innerHTML=skillGroups[group].map(skill=>`<span>${skill}</span>`).join('');const index=Object.keys(skillGroups).indexOf(group)+1;$('.skill-count').textContent=`0${index} — 05`}
function renderProjects(filter='All'){const shown=filter==='All'?projects:projects.filter(project=>project.category===filter||project.tag.includes(filter));$('#project-grid').innerHTML=shown.map((project,index)=>`<article class="project-card ${project.featured?'featured':''} reveal visible"><div class="project-top"><span class="tag">${project.tag}</span><span class="project-index">0${projects.indexOf(project)+1}</span></div><h3>${project.title}</h3><p>${project.description}</p><div class="project-bottom"><div><div class="tech-row">${project.tech.map(tech=>`<span>${tech}</span>`).join('')}</div>${project.metrics?`<small class="project-metrics">${project.metrics}</small>`:''}</div><button class="project-open" data-project="${projects.indexOf(project)}" aria-label="Open details for ${project.title}"><i data-lucide="arrow-up-right"></i></button></div></article>`).join('');lucide.createIcons();$$('.project-open').forEach(button=>button.addEventListener('click',()=>openModal(Number(button.dataset.project))))}
function renderExperience(){$('#experience-list').innerHTML=experience.map((item,index)=>`<article class="timeline-item reveal"><div><small>0${index+1} / ${item[2]}</small><h3>${item[0]}</h3></div><p>${item[1]}</p><p>${item[3]}</p></article>`).join('')}
function renderCertifications(){$('#cert-grid').innerHTML=certifications.map((item,index)=>`<article class="cert-card reveal"><span>0${index+1} · ${item[2]}</span><h3>${item[0]}</h3><p>${item[1]}</p></article>`).join('')}
function openModal(index){const project=projects[index];$('#modal-category').textContent=project.tag;$('#modal-title').textContent=project.title;$('#modal-description').textContent=project.description;$('#modal-features').innerHTML=project.features.map(feature=>`<li>${feature}</li>`).join('');$('#modal-tech').innerHTML=project.tech.map(tech=>`<span>${tech}</span>`).join('');$('#modal-status').textContent=project.status;const link=$('#modal-github');if(project.github){link.href=project.github;link.style.display='inline-flex'}else{link.removeAttribute('href');link.style.display='none'}$('#project-modal').classList.add('open');$('#project-modal').setAttribute('aria-hidden','false');lucide.createIcons()}
function closeModal(){$('#project-modal').classList.remove('open');$('#project-modal').setAttribute('aria-hidden','true')}
renderSkills();renderProjects();renderExperience();renderCertifications();
lucide.createIcons();
$$('.skill-tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.skill-tab').forEach(item=>item.classList.remove('active'));tab.classList.add('active');renderSkills(tab.dataset.skill)}));
$$('.filter').forEach(filter=>filter.addEventListener('click',()=>{$$('.filter').forEach(item=>item.classList.remove('active'));filter.classList.add('active');renderProjects(filter.dataset.filter)}));
$('.modal-close').addEventListener('click',closeModal);$('.modal-backdrop').addEventListener('click',closeModal);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal()});
$('.menu-toggle').addEventListener('click',()=>{$('.nav-links').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',$('.nav-links').classList.contains('open'))});$$('.nav-links a').forEach(link=>link.addEventListener('click',()=>$('.nav-links').classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.13});$$('.reveal').forEach(element=>observer.observe(element));
